algoritmo "exercicio24"
var
   quantia_inicial,dolar,marco,libra:inteiro
inicio
   escreva("Escreva o valor que você possui para viajar: ")
   leia(quantia_inicial)
   escreva("Você possui ", quantia_inicial * 0.8)
   escreval(" dólar(s)")
   escreva("Você possui ", quantia_inicial * 0.57)
   escreval(" marco(s) alemão(s)")
   escreva("Você possui ", quantia_inicial * 0.5)
   escreval(" libra(s) esterlina(s)")
fimalgoritmo
