algoritmo "exercicio9"
var
   altura,base_menor,base_maior:real
inicio
   escreval("Calculando a área do trapézio...")
   escreva("Escreva o tamanho da base menor: ")
   leia(base_menor)
   escreva("Escreva o tamanho da base maior: ")
   leia(base_maior)
   escreva("Escreva a altura: ")
   leia(altura)
   escreva("A área do trapézio é: ", ((base_maior + base_menor) * altura) / 2)
fimalgoritmo
